### ISSUE TITLE
fix: `/[channel]` 라우트 충돌 수정 요청

### ISSUE THREAD

**Issue by DonggyunKim00** [9oormthon-2523/chzzk-clone#37]
## 📝 Description
현재 치지직은 `https://studio.chzzk~~.com`와 같은 서브도메인을 이용해 스튜디오 페이지를 구분하고 있지만, 저희 프로젝트는 라우트 방식으로 스튜디오 페이지를 관리하고 있습니다. 이에 따라, 치지직 스튜디오 페이지 `/`는 저희 프로젝트의 `/studio`에 해당한다고 이해해 주세요.

치지직의 경우, `/`로 접근 시 쿠키에서 유저 `uid` 값을 가져와 `/[uid]`로 리다이렉트됩니다. 하지만 저희 프로젝트에서는 폴더 라우트가 `/[channel]`로 되어 있어 `/studio`로 접근했을 때 채널페이지로 라우팅되는 문제가 발생했습니다. 🥲

이 문제를 해결하기 위해 `/[channel]`를 `/channel/[uid]` 형식의 폴더 라우트로 수정 요청드리고자 합니다.

혹시 더 나은 대안이 있다면 코멘트 남겨주세요!

## ETC
치지직 스튜디오페이지: https://studio.chzzk.naver.com/

**Comment by Layla-Yun** [comment]
확인했습니다!
저도 확인해보니 그런 오류가 있었네요 ... 말씀해주신대로 바꾸는게 좋아보입니다🤔
수정 후 올려보겠습니다!🙇‍♀️
